### ISSUE TITLE
Error in ValidateVR.cs

### ISSUE THREAD

**Issue by thedavidpeterson** [Will9371/Playcraft#5]
Hi! 

Can't get this to build unfortunately (see image)..

The using UnityEngin.XR.Management; is complaining on .Management

The compiler also complains that the type or namespace name "XRGeneralSettings" could not be found.

I installed this with a project open and pressed "Playcraft Install.unitypackage". Also installed various XR packages. 

![image](https://user-images.githubusercontent.com/16776461/144078284-6d9c7a92-22ed-4609-a257-804fbb636fb6.png)

**Comment by Will9371** [comment]
I haven't updated the Unity plugin for a while, so that may be the cause.  As this points to a core functionality issue, I'll make sure to provide a fix as soon as I can.  

In the meanwhile, if that is the only error, you can comment out the script, as it is a minor and independent quality-of-life script (turns on and off a VR setting and has a hook for activating/deactivating objects to save time when switching between flatscreen and VR in editor).

**Comment by Will9371** [comment]
Pushed an update which should fix the issue, please let me know if it works.  Relevant change puts that code inside platform dependent (editor only) compilation.

**Comment by thedavidpeterson** [comment]
Thank you! Now it works =D Although I can only move by teleporting?



David Peterson

+46 72 889 5218

Website <https://davidpeterson.io/> | LinkedIn
<https://www.linkedin.com/in/the-david-peterson/> | Instagram
<https://www.instagram.com/thedavidpeterson/>

**Comment by Will9371** [comment]
I assume you are looking at the VR exploration scene.  The XR rig prefab in that scene can teleport and climb.  The climbing feature has a (optional) ability to extend its reach by holding the grip button.  Other VR locomotion systems include an experimental variation on climbing that grabs automatically (Monkey Climb scene) and pull-based movement (as seen in Gorn).  I've been considering a means for refactoring to make the abilities togglable within a single component without sacrificing modularity or efficiency. 

I've updated the Readme to better describe the context and intent of this repo.  This is not a commercial asset in development that happens to be free (like VRTK), it's where I put my reusable code built for other projects so I can prototype faster on new projects, publicly shared because "why not".  As such, new features are added on a "whenever" basis.

**Comment by thedavidpeterson** [comment]
Got it! Many thanks for sharing and updating this, so cool!
